version: '3.8'
services: 
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        command: yarn start
        container_name: frontend
        ports:
            - "3000:3000"        
        volumes: 
            - ./frontend:/frontend
        image: app:react
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "5001:5001"        
        volumes: 
            - ./backend:/backend